version: "3.9"  # optional since v1.27.0

services:
  app:
    build:
      context: ./
      dockerfile: Dockerfile
    container_name: amonycoffemis-app
    ports:
      - "5200:80"
    
  db:
    image: keinos/sqlite3
    container_name: amonycoffemis-db
    volumes:
     - ./Data:/Data/
    ports: # not actually needed, because the two services are on the same network
      - "3234:3234" 
    tty: true
